import { Injectable, Inject, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { and, desc, eq, gt, gte, isNull, lte, sql } from 'drizzle-orm';
import {
  type Database,
  products,
  productAvailabilityWindows,
  orderItems,
  newsletterCampaigns,
  newsletterSubscribers,
  tenants,
} from '@fermeribg/db';
import { DB_TOKEN } from '../../common/drizzle/drizzle.constants';
import { EmailService } from '../../common/email/email.service';
import { bgToday } from '../../common/time/bg-time';
import { NewsletterService } from './newsletter.service';
import { NewsletterCopyService } from './auto-draft.ai';
import { assembleNewsletterBlocks, type DraftProduct } from './auto-draft.render';

const CAP = 6;
const NEW_DAYS = 7;

export type GenResult =
  | { created: true; campaignId: string }
  | { created: false; reason: 'exists' | 'no-content' };

@Injectable()
export class NewsletterDraftService {
  private readonly logger = new Logger(NewsletterDraftService.name);

  constructor(
    @Inject(DB_TOKEN) private readonly db: Database,
    private readonly email: EmailService,
    private readonly config: ConfigService,
    private readonly newsletter: NewsletterService,
    private readonly copy: NewsletterCopyService,
  ) {}

  /** Tenants opted in (settings.autoNewsletter=true), not demo, with ≥1 active subscriber. */
  async eligibleTenantIds(): Promise<string[]> {
    const rows = await this.db
      .select({ id: tenants.id })
      .from(tenants)
      .where(
        and(
          eq(tenants.isDemo, false),
          sql`coalesce(${tenants.settings}->>'autoNewsletter','false') = 'true'`,
          sql`exists (select 1 from ${newsletterSubscribers} ns where ns.tenant_id = ${tenants.id} and ns.unsubscribed_at is null)`,
        ),
      );
    return rows.map((r) => r.id);
  }

  /** Persist the opt-in flag (jsonb merge, mirroring tenants.service settings writers). */
  async setAutoNewsletter(tenantId: string, enabled: boolean): Promise<{ enabled: boolean }> {
    await this.db
      .update(tenants)
      .set({
        settings: sql`jsonb_set(coalesce(${tenants.settings}, '{}'::jsonb), array['autoNewsletter'], ${JSON.stringify(enabled)}::jsonb, true)`,
      })
      .where(eq(tenants.id, tenantId));
    return { enabled };
  }

  /** Current opt-in state for the tenant. */
  async getAutoNewsletter(tenantId: string): Promise<{ enabled: boolean }> {
    const [t] = await this.db
      .select({ v: sql<boolean>`coalesce(${tenants.settings}->>'autoNewsletter','false') = 'true'` })
      .from(tenants)
      .where(eq(tenants.id, tenantId))
      .limit(1);
    return { enabled: !!t?.v };
  }

  /** Does the tenant already have an unreviewed (draft) auto-generated campaign? */
  private async hasPendingAutoDraft(tenantId: string): Promise<boolean> {
    const [row] = await this.db
      .select({ id: newsletterCampaigns.id })
      .from(newsletterCampaigns)
      .where(
        and(
          eq(newsletterCampaigns.tenantId, tenantId),
          eq(newsletterCampaigns.status, 'draft'),
          eq(newsletterCampaigns.autoGenerated, true),
        ),
      )
      .limit(1);
    return !!row;
  }

  /** Mix: new (7d) + available-now + best-seller fallback, deduped, capped at CAP. */
  async gatherFreshProducts(tenantId: string): Promise<DraftProduct[]> {
    const cols = {
      id: products.id,
      name: products.name,
      priceStotinki: products.priceStotinki,
      imageUrl: products.imageUrl,
    };
    const live = and(
      eq(products.tenantId, tenantId),
      eq(products.isActive, true),
      eq(products.needsReview, false),
      isNull(products.deletedAt),
    );

    const fresh = await this.db
      .select(cols)
      .from(products)
      .where(and(live, gte(products.createdAt, sql`now() - interval '${sql.raw(String(NEW_DAYS))} days'`)))
      .orderBy(desc(products.createdAt))
      .limit(CAP);

    const today = bgToday();
    const available = await this.db
      .selectDistinct(cols)
      .from(products)
      .innerJoin(productAvailabilityWindows, eq(productAvailabilityWindows.productId, products.id))
      .where(
        and(
          live,
          lte(productAvailabilityWindows.startsAt, today),
          gte(productAvailabilityWindows.endsAt, today),
          gt(productAvailabilityWindows.remaining, 0),
        ),
      )
      .limit(CAP);

    const merged: DraftProduct[] = [];
    const seen = new Set<string>();
    for (const p of [...fresh, ...available]) {
      if (seen.has(p.id)) continue;
      seen.add(p.id);
      merged.push({ id: p.id, name: p.name, priceStotinki: p.priceStotinki, imageUrl: p.imageUrl ?? null });
      if (merged.length >= CAP) break;
    }
    if (merged.length > 0) return merged;

    // Fallback: top sellers by order-item count (static-catalog farms still get a draft).
    const best = await this.db
      .select({ ...cols, n: sql<number>`count(${orderItems.id})::int` })
      .from(orderItems)
      .innerJoin(products, eq(orderItems.productId, products.id))
      .where(live)
      .groupBy(products.id, products.name, products.priceStotinki, products.imageUrl)
      .orderBy(desc(sql`count(${orderItems.id})`))
      .limit(CAP);
    return best.map((p) => ({ id: p.id, name: p.name, priceStotinki: p.priceStotinki, imageUrl: p.imageUrl ?? null }));
  }

  private async loadTenant(tenantId: string): Promise<{ name: string; email: string | null; settings: unknown } | null> {
    const [t] = await this.db
      .select({ name: tenants.name, email: tenants.email, settings: tenants.settings })
      .from(tenants)
      .where(eq(tenants.id, tenantId))
      .limit(1);
    return t ?? null;
  }

  private async markAutoGenerated(campaignId: string, tenantId: string): Promise<void> {
    await this.db
      .update(newsletterCampaigns)
      .set({ autoGenerated: true })
      .where(and(eq(newsletterCampaigns.id, campaignId), eq(newsletterCampaigns.tenantId, tenantId)));
  }

  private shopUrl(settings: unknown): string | undefined {
    const s = (settings ?? {}) as Record<string, unknown>;
    return typeof s.siteUrl === 'string' && s.siteUrl ? s.siteUrl : undefined;
  }

  private async notifyFarmer(email: string, campaignId: string): Promise<void> {
    const panel = this.config.get<string>('PUBLIC_APP_URL') ?? 'http://localhost:3000';
    const link = `${panel}/newsletter`;
    const html = `<!DOCTYPE html><html lang="bg"><body style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#333">
  <h1 style="font-size:20px;color:#2d6a4f">Готов бюлетин за преглед</h1>
  <p style="font-size:14px;color:#555">Подготвихме чернова на седмичен бюлетин с пресните ти продукти. Прегледай, редактирай и изпрати с един клик.</p>
  <p><a href="${link}" style="display:inline-block;background:#2d6a4f;color:#fff;text-decoration:none;padding:10px 18px;border-radius:8px;font-weight:bold">Отвори бюлетина</a></p>
  <p style="font-size:12px;color:#999;margin-top:24px">ФермериБГ — автоматична чернова. Нищо не се изпраща без твоето одобрение.</p>
</body></html>`;
    const text = `Готов бюлетин за преглед\n\nПодготвихме чернова на седмичен бюлетин. Отвори: ${link}\n\nНищо не се изпраща без твоето одобрение.`;
    await this.email.sendMail({ to: email, subject: 'Готов бюлетин за преглед — ФермериБГ', html, text });
  }

  /** Build + save one tenant's weekly auto-draft. Dedup + skip-empty; never auto-sends. */
  async generateForTenant(tenantId: string): Promise<GenResult> {
    if (await this.hasPendingAutoDraft(tenantId)) return { created: false, reason: 'exists' };

    const featured = await this.gatherFreshProducts(tenantId);
    if (featured.length === 0) return { created: false, reason: 'no-content' };

    const tenant = await this.loadTenant(tenantId);
    const farmName = tenant?.name ?? 'Фермата';
    const copy = await this.copy.writeCopy(farmName, featured);
    const blocks = assembleNewsletterBlocks(copy, featured, this.shopUrl(tenant?.settings));

    const campaign = await this.newsletter.createCampaign(tenantId, { subject: copy.subject, blocks });
    await this.markAutoGenerated(campaign.id, tenantId);

    if (tenant?.email) {
      try {
        await this.notifyFarmer(tenant.email, campaign.id);
      } catch (e) {
        this.logger.warn(`[newsletter-draft] notify failed tenant=${tenantId}: ${String((e as Error)?.message ?? e)}`);
      }
    }
    this.logger.log(`[newsletter-draft] draft ${campaign.id} for tenant=${tenantId}`);
    return { created: true, campaignId: campaign.id };
  }
}
