import { NewsletterDraftService } from './newsletter-draft.service';

const PRODUCTS = [{ id: 'a', name: 'Домати', priceStotinki: 250, imageUrl: null }];

function makeSvc(over: {
  pending?: boolean;
  products?: any[];
  tenant?: { name: string; email: string | null; settings: unknown } | null;
} = {}) {
  const db = {} as any;
  const email = { sendMail: jest.fn().mockResolvedValue(undefined) };
  const config = { get: (k: string, d?: unknown) => (k === 'PUBLIC_APP_URL' ? 'https://panel.bg' : d) };
  const newsletter = { createCampaign: jest.fn().mockResolvedValue({ id: 'camp1' }) };
  const copy = { writeCopy: jest.fn().mockResolvedValue({ subject: 'Свежо', intro: 'Здр', blurbs: {} }) };
  const svc = new NewsletterDraftService(db, email as any, config as any, newsletter as any, copy as any);
  (svc as any).hasPendingAutoDraft = jest.fn().mockResolvedValue(over.pending ?? false);
  (svc as any).gatherFreshProducts = jest.fn().mockResolvedValue(over.products ?? PRODUCTS);
  (svc as any).loadTenant = jest.fn().mockResolvedValue(
    over.tenant ?? { name: 'Зелена Ферма', email: 'farm@bg', settings: { siteUrl: 'https://shop.bg' } },
  );
  (svc as any).markAutoGenerated = jest.fn().mockResolvedValue(undefined);
  return { svc, email, newsletter, copy };
}

describe('NewsletterDraftService.generateForTenant', () => {
  it('skips when an unreviewed auto-draft already exists', async () => {
    const { svc, newsletter } = makeSvc({ pending: true });
    expect(await svc.generateForTenant('t1')).toEqual({ created: false, reason: 'exists' });
    expect(newsletter.createCampaign).not.toHaveBeenCalled();
  });

  it('skips when there is no fresh content', async () => {
    const { svc, newsletter } = makeSvc({ products: [] });
    expect(await svc.generateForTenant('t1')).toEqual({ created: false, reason: 'no-content' });
    expect(newsletter.createCampaign).not.toHaveBeenCalled();
  });

  it('creates a draft, marks it auto-generated, and notifies the farmer', async () => {
    const { svc, newsletter, email, copy } = makeSvc();
    const res = await svc.generateForTenant('t1');
    expect(res).toEqual({ created: true, campaignId: 'camp1' });
    expect(copy.writeCopy).toHaveBeenCalledWith('Зелена Ферма', PRODUCTS);
    expect(newsletter.createCampaign).toHaveBeenCalledTimes(1);
    const arg = newsletter.createCampaign.mock.calls[0][1];
    expect(arg.subject).toBe('Свежо');
    expect(Array.isArray(arg.blocks)).toBe(true);
    expect((svc as any).markAutoGenerated).toHaveBeenCalledWith('camp1', 't1');
    expect(email.sendMail).toHaveBeenCalledTimes(1);
    expect(email.sendMail.mock.calls[0][0].to).toBe('farm@bg');
  });

  it('still creates the draft when the farm has no email (just no notify)', async () => {
    const { svc, email } = makeSvc({ tenant: { name: 'Ф', email: null, settings: {} } });
    const res = await svc.generateForTenant('t1');
    expect(res).toEqual({ created: true, campaignId: 'camp1' });
    expect(email.sendMail).not.toHaveBeenCalled();
  });
});
